name: EAS Build
on:
  workflow_dispatch:
    inputs:
      platform:
        type: choice
        description: Platform to build for
        options:
          - android
          - ios
      profile:
        type: choice
        description: Build profile to use
        options:
          - development
          - preview
          - production
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18.x]
    steps:
    - name: 🏗 Setup repo
      uses: actions/checkout@v2

    - name: 🏗 Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node }}
        cache: yarn

    - name: 🏗 Setup Expo and EAS
      uses: expo/expo-github-action@v7
      with:
        token: ${{ secrets.EXPO_TOKEN }}
        expo-version: latest
        eas-version: latest

    - name: 👷 Build app
      run: |
        eas build \
          --non-interactive \
          --platform=${{ github.event.inputs.platform }} \
          --profile=${{ github.event.inputs.profile }}